### ISSUE TITLE
Can not work on Minecraft 1.20.1 in Windows11

### ISSUE THREAD

**Issue by yunsmall** [EBMare/RconCpp#2]
it can run normally when running constructor function and connect function, but when running authenticate func it makes the program blocked, after a while sever shows "Thread RCON Client /127.0.0.1 shutting down", then the program continue running without throwing Exception, and when running sendAndRecv, the program shows several lines of "error"

**Comment by Mare-02** [comment]
Can you provide some Code so I can take a look at it and help you as fast as I can

**Comment by yunsmall** [comment]
Same code as in your example code file, but I have changed the command into a Minecraft command like "help" or "setblock", perhaps they have defferent RCON protocols?

**Comment by Mare-02** [comment]
No they use the same Source Rcon Protocol. Comment line 82: recv(id, type, packet_size); // recv "shadow" packet
 in the RconCpp.cpp file
and try again

**Comment by EBMare** [comment]
Another solution to this problem could be that you arent using a little endian system and my authentication code is lacking this compatibility. I will edit this later and contact you, so you can clone the new code

**Comment by yunsmall** [comment]
Well, after I commented line 82: recv(id, type, packet_size);, it worked properly.

**Comment by Mare-02** [comment]
It looks like Minecraft isnt receiving the "shadow packet" before the authentication. I tested this on squad and this was necessary.

**Comment by Mare-02** [comment]
@yunsmall I updated the code.
